apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secretConfig }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
